spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/rbac_db
spring.datasource.username=root
spring.datasource.password=Ser553()()

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true